import { checkCommandFor, sanitizeNagiosValue } from '@/domain/checks';
import { buildTargetHostMap, planHosts } from '@/domain/topology';
import type { Target, TargetKind } from '@/domain/types';

const HOST_GROUP_BY_KIND: Record<TargetKind, string> = {
  device: 'monitoring-devices',
  application: 'monitoring-applications',
  service: 'monitoring-services',
};

const HOST_GROUP_ALIAS: Record<TargetKind, string> = {
  device: 'Monitored devices',
  application: 'Monitored applications',
  service: 'Monitored services',
};

export interface NagiosConfigBundle {
  hosts: string;
  services: string;
  hostCount: number;
  serviceCount: number;
  disabled: Target[];
}

export interface GenerateOptions {
  /** Fixed timestamp for reproducible output (tests, diffs). */
  generatedAt?: string;
}

type Attribute = readonly [key: string, value: string];

function renderObject(kind: 'host' | 'service' | 'hostgroup', attributes: Attribute[]): string {
  const width = attributes.reduce((max, [key]) => Math.max(max, key.length), 0);
  const lines = attributes.map(([key, value]) => `    ${key.padEnd(width)}    ${value}`);
  return [`define ${kind} {`, ...lines, '}'].join('\n');
}

function banner(title: string, generatedAt: string): string {
  const rule = '#'.repeat(78);
  return [
    rule,
    `# ${title}`,
    `# Generated by the monitoring interface on ${generatedAt}.`,
    '# Regenerate from the interface rather than editing: manual changes are lost.',
    rule,
  ].join('\n');
}

/**
 * Render the target registry as Nagios object configuration.
 *
 * Hosts are deduplicated per address; each enabled target becomes one service on
 * its address's host. Disabled targets are emitted as comments so an operator can
 * see exactly what was excluded and why the host count looks the way it does.
 */
export function generateNagiosConfig(
  targets: readonly Target[],
  options: GenerateOptions = {},
): NagiosConfigBundle {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const enabled = targets.filter((target) => target.enabled);
  const disabled = targets.filter((target) => !target.enabled);

  const plans = planHosts(enabled);
  const hostNames = buildTargetHostMap(plans);

  const usedKinds = new Set<TargetKind>();
  for (const plan of plans) {
    for (const kind of plan.kinds) {
      usedKinds.add(kind);
    }
  }

  const hostGroupBlocks = [...usedKinds]
    .sort()
    .map((kind) =>
      renderObject('hostgroup', [
        ['hostgroup_name', HOST_GROUP_BY_KIND[kind]],
        ['alias', HOST_GROUP_ALIAS[kind]],
      ]),
    );

  const hostBlocks = plans.map((plan) =>
    renderObject('host', [
      ['use', 'monitor-host'],
      ['host_name', plan.hostName],
      ['alias', plan.address],
      ['address', sanitizeNagiosValue(plan.address)],
      ['hostgroups', plan.kinds.map((kind) => HOST_GROUP_BY_KIND[kind]).join(',')],
    ]),
  );

  const serviceBlocks = enabled.map((target) =>
    renderService(target, hostNames.get(target.id) ?? ''),
  );

  const hostsHeader = banner('Hosts and host groups', generatedAt);
  const hostsBody = [...hostGroupBlocks, ...hostBlocks].join('\n\n');

  const servicesHeader = banner('Services', generatedAt);
  const servicesBody = serviceBlocks.length > 0 ? serviceBlocks.join('\n\n') : '# No enabled targets.';

  const disabledNote =
    disabled.length === 0
      ? ''
      : [
          '',
          '',
          banner('Disabled targets (not generated)', generatedAt),
          disabled
            .map(
              (target) =>
                `# ${sanitizeNagiosValue(target.name)} @ ${sanitizeNagiosValue(target.address)}`,
            )
            .join('\n'),
        ].join('\n');

  return {
    hosts: `${hostsHeader}\n\n${hostsBody}\n`,
    services: `${servicesHeader}\n\n${servicesBody}${disabledNote}\n`,
    hostCount: hostBlocks.length,
    serviceCount: serviceBlocks.length,
    disabled,
  };
}

function renderService(target: Target, hostName: string): string {
  const attributes: Attribute[] = [
    ['use', 'monitor-service'],
    ['host_name', hostName],
    ['service_description', sanitizeNagiosValue(target.name)],
    ['check_command', checkCommandFor(target)],
    ['check_interval', String(target.checkIntervalMinutes)],
    ['retry_interval', String(target.retryIntervalMinutes)],
    ['max_check_attempts', String(target.maxAttempts)],
    ['_target_id', sanitizeNagiosValue(target.id)],
    ['_target_kind', target.kind],
    ['_target_check', target.check],
  ];

  if (target.notes) {
    attributes.push(['notes', sanitizeNagiosValue(target.notes)]);
  }

  return renderObject('service', attributes);
}

/**
 * The host + service definition for a single target, used by the detail view so
 * an operator can see precisely what will be deployed for the thing they added.
 */
export function generateTargetSnippet(target: Target): string {
  const plans = planHosts([target]);
  const plan = plans[0];

  if (!plan) {
    return '# No address set for this target.';
  }

  const host = renderObject('host', [
    ['use', 'monitor-host'],
    ['host_name', plan.hostName],
    ['alias', plan.address],
    ['address', sanitizeNagiosValue(plan.address)],
    ['hostgroups', plan.kinds.map((kind) => HOST_GROUP_BY_KIND[kind]).join(',')],
  ]);

  return `${host}\n\n${renderService(target, plan.hostName)}`;
}
